"""add repository description

Revision ID: 34c6c14ce1b9
Revises: fdd9f6003b0d
Create Date: 2026-06-05 12:00:17.789022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c6c14ce1b9'
down_revision: Union[str, Sequence[str], None] = 'fdd9f6003b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'description')
    # ### end Alembic commands ###
