"""create repositories table

Revision ID: fdd9f6003b0d
Revises: 1bc8fba999dc
Create Date: 2026-06-04 16:46:02.516508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd9f6003b0d'
down_revision: Union[str, Sequence[str], None] = '1bc8fba999dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_id', sa.BigInteger(), nullable=False))
    op.add_column('repositories', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('repositories', sa.Column('default_branch', sa.String(length=100), nullable=False))
    op.add_column('repositories', sa.Column('language', sa.String(length=100), nullable=True))
    op.add_column('repositories', sa.Column('stars', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'repositories', ['github_id'])
    op.drop_column('repositories', 'github_repo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_repo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'repositories', type_='unique')
    op.drop_column('repositories', 'stars')
    op.drop_column('repositories', 'language')
    op.drop_column('repositories', 'default_branch')
    op.drop_column('repositories', 'full_name')
    op.drop_column('repositories', 'github_id')
    # ### end Alembic commands ###
